collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.1079484
color:
  saturation: 0.6160043
  brandStrength: 0.5257788
  lightness: 0.4215897
  brandColors:
    - '#000000'
    - '#3C3E3B'
    - '#54D9FC'
    - '#B0636D'
    - '#E6E5E6'
  rhythmicContrast: 0.8039742
layout_spectrum: 1
name: GeoffDuquette
